config/routes.rb
BWriter::Application.routes.draw do
  devise_for :users
  root to: "users#index"
  resources :users, only: :show
  resources :blurts
  resources :upvotes
  resources :shows
end

app/models/blurt.rb
class Blurt < ActiveRecord::Base
  belongs_to :user
  has_many :upvotes
  has_and_belongs_to_many :shows

  def self.best_blurt
    Blurt.order(approval: :desc).first
  end

  def self.blurt_vote_freq
    freq = Hash.new(0)
    Upvote.all.each{|upvote| freq[upvote.blurt_id] += 1}
    freq.sort_by{|blurt_id, upvotes| upvotes}.reverse
  end

  # def self.order_by_approval
  #   self.order(approval: :desc)
  # end

  def update_approval
    new_approval = (self.upvotes.length.to_f / self.shows.length.to_f) * 100
    self.update(approval: new_approval.to_i)
  end

end

app/models/show.rb
class Show < ActiveRecord::Base
  has_one :upvote
  has_and_belongs_to_many :blurts

end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :blurt
  belongs_to :show
  def self.two_blurts
    blurt_ids = []
    Blurt.all.each do |b|
      blurt_ids << b.id
    end
    blurt1  = blurt_ids.sample
    blurt_ids.delete(blurt1)
    blurt2 = blurt_ids.sample
    blurt_ids.delete(blurt2)
    [Blurt.find(blurt1), Blurt.find(blurt2)]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar
  has_many :blurts
  has_many :shows

  def needs_to_blurt?
      result = false
      if self.ever_blurted?
        result = (DateTime.now - self.last_blurt).to_i >= 1
      else
        result = true
      end
      result
  end

  def ever_blurted?
    self.blurts.last
  end

  def last_blurt
    self.blurts.last.created_at.to_datetime
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/blurts_controller.rb
class BlurtsController < ApplicationController

  def create
    @blurt = Blurt.create(blurt_params)
    current_user.blurts << @blurt
    redirect_to :back
  end

  private

  def blurt_params
    params.require(:blurt).permit(:content)
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def new
    @blurt1, @blurt2 = Upvote.two_blurts
    @show = Show.create(:user_id => current_user.id)
    @show.blurts << @blurt1
    @show.blurts << @blurt2
    @blurt1.update_approval
    @blurt2.update_approval
  end


  private

  def show_params
    params.require(:show).permit(:user_id)
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController

  def new
    @blurt1, @blurt2 = Upvote.two_blurts
  end

  def create
    @upvote = Upvote.create(vote_params)
    @upvote.update(user_id: current_user.id)
    @upvote.blurt.update_approval
    redirect_to upvotes_path
  end

  def index
    @best_blurt = Blurt.best_blurt
    @blurts = Blurt.order(:approval => :desc)
    @vote_quantity = Upvote.where(blurt_id: @best_blurt.id).length

  end

  def show
  end

  private
  def vote_params
    params.require(:upvote).permit(:blurt_id, :show_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id])
    @blurt = Blurt.new
    @blurts = @user.blurts
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def index
  end

  def new
    @blurt1
    @blurt2

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blurts_helper.rb
module BlurtsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>betterBlurter</title>
  <%= favicon_link_tag image_path('favicon.ico') %>
  <%= stylesheet_link_tag    "application", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application",  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "data-turbolinks-track" => true %>
  <title><%= yield :title %></title>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%=root_path%>">betterBlurter</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">

    </ul>
    <!--
    <form class="navbar-form navbar-left" id="listingSearch" action='/listings' data-remote="true">
      <input type="text" class="form-control col-lg-8" id="search" placeholder="Search" name='search'>

    </form>
  -->
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to current_user.username, user_path(current_user) %></li>

      <% else %>
        <li><a href="<%= new_user_session_path %>">Sign In</a></li>
         <li><a href="<%= new_user_registration_path %>">Sign Up</a></li>
      <% end %>
    </ul>
  </div>
  </div>
  <div class="container">

  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>
    <%= yield %>
  <div class="results">
  </div>

</div>
</body>
</html>

app/views/shows/new.html.erb
<h1> Choose the best! </h1>

<div class="left">
  <div class=".col-xs-6">
    <p><%= simple_format(@blurt1.content) %></p>

    <%=link_to "Up Vote", upvotes_path(:upvote => {blurt_id: @blurt1.id, :show_id => @show.id}), method: :post, class: 'btn btn-primary' %>
  </div>
</div>

<div class="left">
  <div class="col-xs-6">
    <p><%= simple_format(@blurt2.content) %></p>

    <%=link_to "Up Vote", upvotes_path(:upvote => {blurt_id: @blurt2.id, :show_id => @show.id}), method: :post, class: 'btn btn-primary' %>

  </div>
</div>

app/views/upvotes/index.html.erb
<h1> BLURT OF THE DAY! </h1>


<div class="best-blurt">
   <h3> <%= simple_format(@best_blurt.content)  %></h3>
   <h4> Congratulations <%= User.find(@best_blurt.user_id).username %>! </h4>
   <h5> <%= User.find(@best_blurt.user_id).username %> received  <%= @vote_quantity %> votes. </h5>
   <h5> It's approval rating is <%= @best_blurt.approval %> % </h5>
</div>
<h2> Some more great blurts </h2>

<% @blurts.each do |b| %>
<div class="blurt">
  <p> <%= simple_format(b.content) %> by <em> <%= b.user.username %> </em><p>
  <p> <%= b.approval %>% approval with <%= b.upvotes.length %> upvotes </p>
</div>
<% end %>

app/views/users/index.html.erb
<% if current_user %>
  <% if current_user.needs_to_blurt? && current_user.ever_blurted? %>
    <p> It has been <%= time_ago_in_words(current_user.last_blurt) %> since your last blurt. It is time to blurt again!<p>
    <div class="main">
      <%= link_to "Blurt!", user_path(current_user),  class: 'btn btn-primary btn-lg'%>
    </div>
  <% elsif !current_user.ever_blurted? %>
  <p>Welcome to better blurter, where everyone blurts and everyone votes! Click the button below to make your first blurt!</p>
    <div class="main">
      <%= link_to "Blurt!", user_path(current_user),  class: 'btn btn-primary btn-lg'%>
    </div>
  <% else %>
  <div class="centered">
    <%= link_to "Vote on random Blurts!", new_show_path,  class: "btn btn-primary btn-lg" %>
  </div>
  <% end %>

<% else %>

<h2>Welcome to betterBlurt</h2>
<h4> The worlds largest writing contest with a new winner every day!</h4>
<% end %>

app/views/users/show.html.erb
<h1> Welcome back <%= current_user.username %></h1>

<ul>
  <% @blurts.each do |b| %>
    <li> <%= b.content %>  |   <em>blurted</em> <%= time_ago_in_words(b.created_at)  %> ago.</li>
  <% end %>
</ul>

<%= form_for @blurt do |f| %>
   <%= f.text_area(:content, :size => "50x10" ) %>
  <br>
  <%= f.submit "Blurt!", :class => "btn btn-primary" %>
<% end %>

<br>

<% if current_user.blurts.count > 0 %>
  <%= link_to "Vote on random Blurts!", new_upvote_path,  class: "btn btn-primary" %>
<% end %>